# Generated by Django 6.0.2 on 2026-02-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_task_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubTask',
        ),
    ]
